### ISSUE TITLE
损失函数问题

### ISSUE THREAD

**Issue by kk-kaii** [xiaoxiangAQ/GAS-Net#4]
作者大大 之前那个数据集读取我已经解决了 我看你论文中用的损失函数是bce和dice的混合函数 但是您提供的源码中只用了bce 是否源码不完整？ 望回复 感谢

**Comment by xiaoxiangAQ** [comment]
您好，我们在实验开始设计的是bce和dice的混合函数，但是在后续的实验中发现，GASNet在bce上的精度略高于weighted loss，我们分析方法本身能够对类不平衡问题有所解决，所以不需要特别设计的损失函数。同时，我们在实验中也将weight阈值进行了修改，输出了一系列不同weight阈值loss下的变化检测结果，发现传统参数设置下并不是所采用数据集的最佳参数。因此，我们不建议在实际问题中直接尝试常见参数下的weighted loss，建议有需求的话实验后选择合适的loss。

详见论文中表格8-11

**Comment by kk-kaii** [comment]
> 您好，我们在实验开始设计的是bce和dice的混合函数，但是在后续的实验中发现，GASNet在bce上的精度略高于weighted loss，我们分析方法本身能够对类不平衡问题有所解决，所以不需要特别设计的损失函数。同时，我们在实验中也将weight阈值进行了修改，输出了一系列不同weight阈值loss下的变化检测结果，发现传统参数设置下并不是所采用数据集的最佳参数。因此，我们不建议在实际问题中直接尝试常见参数下的weighted loss，建议有需求的话实验后选择合适的loss。
> 
> 详见论文中表格8-11

好滴 您能提供一下两个数据集的最好效果的权重文件吗 resnet18-0.5，resnet18-0.9以及resnet34-0.5和resnet34-0.9 ，望回复 谢谢您

**Comment by xiaoxiangAQ** [comment]
> > 您好，我们在实验开始设计的是bce和dice的混合函数，但是在后续的实验中发现，GASNet在bce上的精度略高于weighted loss，我们分析方法本身能够对类不平衡问题有所解决，所以不需要特别设计的损失函数。同时，我们在实验中也将weight阈值进行了修改，输出了一系列不同weight阈值loss下的变化检测结果，发现传统参数设置下并不是所采用数据集的最佳参数。因此，我们不建议在实际问题中直接尝试常见参数下的weighted loss，建议有需求的话实验后选择合适的loss。
> > 详见论文中表格8-11
> 
> 好滴 您能提供一下两个数据集的最好效果的权重文件吗 resnet18-0.5，resnet18-0.9以及resnet34-0.5和resnet34-0.9 ，望回复 谢谢您

（1）权重文件较大、实验较多涉及很多模型。同时，本文不是zero shot模型，直接在公开集训练就能获得。

（2）0.5和0.9是test时候separately设置的，并不是两个模型，如resnet18-0.5/resnet18-0.9在同一个数据集下是一个模型。望仔细阅读下论文，谢谢

**Comment by xiaoxiangAQ** [comment]
> > 您好，我们在实验开始设计的是bce和dice的混合函数，但是在后续的实验中发现，GASNet在bce上的精度略高于weighted loss，我们分析方法本身能够对类不平衡问题有所解决，所以不需要特别设计的损失函数。同时，我们在实验中也将weight阈值进行了修改，输出了一系列不同weight阈值loss下的变化检测结果，发现传统参数设置下并不是所采用数据集的最佳参数。因此，我们不建议在实际问题中直接尝试常见参数下的weighted loss，建议有需求的话实验后选择合适的loss。
> > 详见论文中表格8-11
> 
> 好滴 您能提供一下两个数据集的最好效果的权重文件吗 resnet18-0.5，resnet18-0.9以及resnet34-0.5和resnet34-0.9 ，望回复 谢谢您

您好，已上传resnet18下两个数据集的model，由于本论文不是zero-shot思路，其实自己在公开集训练就可以复现论文所有实验模型。
注意： resnet18-0.5/resnet18-0.9在同一个数据集上是一个模型，只是test时候的参数不同。
同时，由于实验过多，模型太多，上传的是Table2、3中resnet18的模型。谢谢理解。
链接：https://pan.baidu.com/s/1ku_ZtdFU6rKzFoon75UkXw 
提取码：edxf
