### ISSUE TITLE
复现结果

### ISSUE THREAD

**Issue by kk-kaii** [xiaoxiangAQ/GAS-Net#5]
您好 我复现了您这篇文章之后 选择了第75个epoch的权重作为预测的权重 但结果为OA: 0.050942644476890564 P值: 0.05094263033483372 R值: 1.0 F1值: 0.09694654848781466 kappa值: 1.5997017025671001e-09 但哪都没改 按照您提供的源码复现的 不知道为啥会出现这种情况 能不能帮忙看看 谢谢

**Comment by youmuzi** [comment]
您好，我不知道为什么出现了爆显存的问题，您这边出现过嘛

**Comment by kk-kaii** [comment]
> 您好，我不知道为什么出现了爆显存的问题，您这边出现过嘛

您好 我出现过一次 跑到第六回合就爆显存了 把bachsize调小后就没出现这种情况了 你复现出来的精度咋样啊

**Comment by youmuzi** [comment]
> > 您好，我不知道为什么出现了爆显存的问题，您这边出现过嘛
> 
> 您好 我出现过一次 跑到第六回合就爆显存了 把bachsize调小后就没出现这种情况了 你复现出来的精度咋样啊

我是第一个回合会爆了显存，不知道为什么，用的是3090，bitchsize设置成2了还是爆显存

**Comment by kk-kaii** [comment]
> > > 您好，我不知道为什么出现了爆显存的问题，您这边出现过嘛
> > 
> > 
> > 您好 我出现过一次 跑到第六回合就爆显存了 把bachsize调小后就没出现这种情况了 你复现出来的精度咋样啊
> 
> 我是第一个回合会爆了显存，不知道为什么，用的是3090，bitchsize设置成2了还是爆显存

不应该把 我是3060都不会报显存

**Comment by xiaoxiangAQ** [comment]
> 您好，我不知道为什么出现了爆显存的问题，您这边出现过嘛

您好，我在最开始另一些自己的数据集中也有遇见过，我认为可以优先考虑是数据读取的问题，检查一下数据读取过程中是否合理释放显存，比如尝试val/test的主程序前加以下代码：

`with torch.no_grad():
        test(input_test, modelfile, network_name, batch_size)`

**Comment by xiaoxiangAQ** [comment]
> 您好 我复现了您这篇文章之后 选择了第75个epoch的权重作为预测的权重 但结果为OA: 0.050942644476890564 P值: 0.05094263033483372 R值: 1.0 F1值: 0.09694654848781466 kappa值: 1.5997017025671001e-09 但哪都没改 按照您提供的源码复现的 不知道为啥会出现这种情况 能不能帮忙看看 谢谢

您好，我也建议先检查一下数据，在读入数据后输入模型前可视化数据和标签，看是否存在问题。论文中的公开集后续也有复现多次，75个epoch时候结果肯定不是您贴的这种精度

**Comment by kk-kaii** [comment]
> > 您好 我复现了您这篇文章之后 选择了第75个epoch的权重作为预测的权重 但结果为OA: 0.050942644476890564 P值: 0.05094263033483372 R值: 1.0 F1值: 0.09694654848781466 kappa值: 1.5997017025671001e-09 但哪都没改 按照您提供的源码复现的 不知道为啥会出现这种情况 能不能帮忙看看 谢谢
> 
> 您好，我也建议先检查一下数据，在读入数据后输入模型前可视化数据和标签，看是否存在问题。论文中的公开集后续也有复现多次，75个epoch时候结果肯定不是您贴的这种精度

好滴 谢谢 这个已经解决了 之前用的多卡跑 但是单卡测试出现了这种情况 用多卡测试就恢复正常了

**Comment by youmuzi** [comment]
> > > > 您好，我不知道为什么出现了爆显存的问题，您这边出现过嘛
> > > 
> > > 
> > > 您好 我出现过一次 跑到第六回合就爆显存了 把bachsize调小后就没出现这种情况了 你复现出来的精度咋样啊
> > 
> > 
> > 我是第一个回合会爆了显存，不知道为什么，用的是3090，bitchsize设置成2了还是爆显存
> 
> 不应该把 我是3060都不会报显存
您这边的bitchsize设置为多少呢

**Comment by youmuzi** [comment]
> > 您好，我不知道为什么出现了爆显存的问题，您这边出现过嘛
> 
> 您好，我在最开始另一些自己的数据集中也有遇见过，我认为可以优先考虑是数据读取的问题，检查一下数据读取过程中是否合理释放显存，比如尝试val/test的主程序前加以下代码：
> 
> `with torch.no_grad(): test(input_test, modelfile, network_name, batch_size)`

您好，我把train里面只存放一组图像，但还是爆显存了，用的是1080，bitchsize为1，在图像读取阶段tensor是[1,3,1024,1024]，显存爆在了module的forward的最后一步， x = self.last_conv(x)。

**Comment by xiaoxiangAQ** [comment]
> > > 您好 我复现了您这篇文章之后 选择了第75个epoch的权重作为预测的权重 但结果为OA: 0.050942644476890564 P值: 0.05094263033483372 R值: 1.0 F1值: 0.09694654848781466 kappa值: 1.5997017025671001e-09 但哪都没改 按照您提供的源码复现的 不知道为啥会出现这种情况 能不能帮忙看看 谢谢
> > 
> > 
> > 您好，我也建议先检查一下数据，在读入数据后输入模型前可视化数据和标签，看是否存在问题。论文中的公开集后续也有复现多次，75个epoch时候结果肯定不是您贴的这种精度
> 
> 好滴 谢谢 这个已经解决了 之前用的多卡跑 但是单卡测试出现了这种情况 用多卡测试就恢复正常了

哈哈，我是单卡跑的，可能是哪里数据处理有些bug，不是单卡的原因

**Comment by xiaoxiangAQ** [comment]
> 

这个我也不太方便帮你调试，建议单步调试一下，用matplotlib看看图像、label对不对。另外，levir-cd官方论文提到，数据处理时候将1024裁剪成了不重叠的256大小，望仔细阅读下

**Comment by youmuzi** [comment]
> > 
> 
> 这个我也不太方便帮你调试，建议单步调试一下，用matplotlib看看图像、label对不对。另外，levir-cd官方论文提到，数据处理时候将1024裁剪成了不重叠的256大小，望仔细阅读下

好的，谢谢

**Comment by youmuzi** [comment]
> 您好 我复现了您这篇文章之后 选择了第75个epoch的权重作为预测的权重 但结果为OA: 0.050942644476890564 P值: 0.05094263033483372 R值: 1.0 F1值: 0.09694654848781466 kappa值: 1.5997017025671001e-09 但哪都没改 按照您提供的源码复现的 不知道为啥会出现这种情况 能不能帮忙看看 谢谢

您好，可以发一份你用的levir-cd数据集给我吗，1173669846@qq.com，谢谢啊
