### ISSUE TITLE
论文对比实验

### ISSUE THREAD

**Issue by kk-kaii** [xiaoxiangAQ/GAS-Net#6]
![image](https://github.com/xiaoxiangAQ/GAS-Net/assets/105615283/be5c6df6-70d7-464d-ac6b-dd09be799e9e)
您好 您在levir_CD数据集中的对比实验部分，FC-EF和FC-Siam_conc和FC-Siam_diff的对比实验都是跑了100个epoch吗 为啥我跑出来的F1精度都在80%多，和您复现的60%多也差距太大了吧

**Comment by wusuowei666** [comment]
你好，看你是复现成功了，请问个问题，
![image](https://github.com/xiaoxiangAQ/GAS-Net/assets/140156818/8d108029-6417-4ae8-98b5-a7f11331746a)
这个数据集的路径要怎么写呢

**Comment by xiaoxiangAQ** [comment]
> ![image](https://user-images.githubusercontent.com/105615283/252585873-be5c6df6-70d7-464d-ac6b-dd09be799e9e.png) 您好 您在levir_CD数据集中的对比实验部分，FC-EF和FC-Siam_conc和FC-Siam_diff的对比实验都是跑了100个epoch吗 为啥我跑出来的F1精度都在80%多，和您复现的60%多也差距太大了吧

The results reported in the paper are the reference points. It's important to note that when reproducing methods, results can sometimes be higher or lower than the original text. Choosing between the highest result and the reproduced result can be challenging, so we've adopted this approach.

**Comment by xiaoxiangAQ** [comment]
> 你好，看你是复现成功了，请问个问题， ![image](https://user-images.githubusercontent.com/140156818/278966450-8d108029-6417-4ae8-98b5-a7f11331746a.png) 这个数据集的路径要怎么写呢

The organization of the data can be found in the “README.md” file.

**Comment by wusuowei666** [comment]
你好，我目前在复现这篇文章的实验，论文中提及使用3090，我使用了3090，但提示显存不足，然后我使用了V100-SXM2-32GB，也提示显存不足，我只修改了数据集路径，其余代码都没动，请问是什么问题呢，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoxiangAQ/GAS-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaoxiangAQ/GAS-Net] 论文对比实验 (Issue #6)





 
Closed #6 as completed.
